### ISSUE TITLE
Ending up on unknown crash

### ISSUE THREAD

**Issue by M-Zubair10** [fengwang/super_resolution#4]
Hi there,
I use your pypi release to upscale images, which is bit too slow process and sometimes program takes too long and finished by returing this error
Process finished with exit code -1073740791 (0xC0000409)
Kindly response ASAP
Thanks!

**Comment by fengwang** [comment]
This error is very likely a result of insufficient memory in the system. Can you try it again on another system with more memory installed? Or you can split you input image and put the results together after super-resolution?

This program is supposed to be slow as (1) it does not use GPU for platform compatibility, and (2) it needs warm up at before executing the super-resolution.
